services:
  - type: web
    name: oubli-app
    env: php
    plan: free
    buildCommand: ""
    startCommand: ""
    rootDir: .
    region: oregon
    envVars:
      - key: DB_HOST
        value: mysql.railway.internal
      - key: DB_PORT
        value: 3306
      - key: DB_NAME
        value: railway
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: rglxfUPkHBidvHHeXYLLLckxROKYJMpB
